"""empty message

Revision ID: ff9da26ed2f3
Revises: 15791a4b1d49
Create Date: 2022-03-29 00:53:34.833106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9da26ed2f3'
down_revision = '15791a4b1d49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=120), nullable=False),
    sa.Column('label', sa.Boolean(create_constraint=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task'),
    sa.UniqueConstraint('task')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
